// Minimal IATA to IANA timezone mapping for demo purposes
// Expand as needed for more airports
const IATA_TZ_MAP: Record<string, string> = {
  ORD: 'America/Chicago',
  AUH: 'Asia/Dubai',
  BKK: 'Asia/Bangkok',
  JFK: 'America/New_York',
  LHR: 'Europe/London',
  CDG: 'Europe/Paris',
  HND: 'Asia/Tokyo',
  IAD: 'America/New_York',
  ATL: 'America/New_York',
  BOS: 'America/New_York',
  YYZ: 'America/Toronto',
  BAH: 'Asia/Bahrain',
  PEK: 'Asia/Shanghai',
  CAI: 'Africa/Cairo',
  AMD: 'Asia/Kolkata',
  BLR: 'Asia/Kolkata',
  MAA: 'Asia/Kolkata',
  DEL: 'Asia/Kolkata',
  HYD: 'Asia/Kolkata',
  JAI: 'Asia/Kolkata',
  COK: 'Asia/Kolkata',
  CCU: 'Asia/Kolkata',
  CCJ: 'Asia/Kolkata',
  TRV: 'Asia/Kolkata',
  BOM: 'Asia/Kolkata',
  DPS: 'Asia/Makassar', // Bali (Denpasar)
  CGK: 'Asia/Jakarta',
  AMM: 'Asia/Amman',
  KWI: 'Asia/Kuwait',
  BEY: 'Asia/Beirut',
  KUL: 'Asia/Kuala_Lumpur',
  MLE: 'Indian/Maldives',
  CMH: 'America/New_York',
  MCT: 'Asia/Muscat',
  ISB: 'Asia/Karachi',
  KHI: 'Asia/Karachi',
  LHE: 'Asia/Karachi',
  MNL: 'Asia/Manila',
  DOH: 'Asia/Qatar',
  JED: 'Asia/Riyadh',
  DMM: 'Asia/Riyadh',
  SEZ: 'Indian/Mahe',
  CMB: 'Asia/Colombo',
  HKT: 'Asia/Bangkok',
  IST: 'Europe/Istanbul',
  RUH: 'Asia/Riyadh',
};

export function getAirportTimezone(iata: string): string | undefined {
  return IATA_TZ_MAP[iata.toUpperCase()];
} 